# Generated by Django 2.1.7 on 2023-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='ssc',
            new_name='colg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='gpacg',
            new_name='gpacolg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='gpasc',
            new_name='gpamasters',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='gpassc',
            new_name='gpascl',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='coursecg',
            new_name='masters',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='uni',
            new_name='scl',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='yearofpassingcg',
            new_name='yearofpassingcolg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='yearofpassingsc',
            new_name='yearofpassingmasters',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='yearofpassingssc',
            new_name='yearofpassingscl',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='coursesc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='coursessc',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='unib',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='unim',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
